server:
  port: 8086
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true # we use Webpack dev server + BrowserSync for livereload
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/adt_web_template
    username: postgres
    password: 1234
    hikari:              # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      pool-name: Hikari
      auto-commit: false
      data-source-properties:
       cachePrepStmts: true
       prepStmtCacheSize: 250
       prepStmtCacheSqlLimit: 2048
       useServerPrepStmts: true
  resources:
    chain:
      compressed: true

  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      chain:
        compressed: true
        cache: true
        strategy:
          content:
            paths: /**
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
